### ISSUE TITLE
Satellites set to "No Power" after loading

### ISSUE THREAD

**Issue by Gschmidt22** [Kerbalight/CommNext#13] opened 2024-02-22 17:39 UTC
I've been having an issue where every time I load a save with the esc menu or quickload, all my satellites are set to a "No Power" state and are rendered useless for communication. This can be "fixed" by taking control of each satellite individually, when I take control of a satellite it regains EC and starts working correctly for communications, even after leaving control of the satellite.

I saved on this:
![image](https://github.com/Kerbalight/CommNext/assets/84433027/fb19a703-0562-4502-a619-be059e746b7a)

and load to this:
![image](https://github.com/Kerbalight/CommNext/assets/84433027/7d5eb713-6c9b-4d2f-9abc-9c90b81ffa30)

I'm not super technical when it comes to games, so if you need logs or other context info let me know how to post it and I will.

**Comment by rockfactory** [comment] 2024-02-24 20:56
Hi @Gschmidt22 thanks for the report! It would be useful to have your save game, so I can try it by myself; anyway it seems specifically related to Quickload, so I have a couple of ideas about this, I'll keep you updated

**Comment by rockfactory** [comment] 2024-02-25 17:04
I'm going to publish a workaround for this in v0.6.0. Please let me know if it helps, and in case, if you could send me the savegame and the log it would be helpful to debug it further

**Comment by Gschmidt22** [comment] 2024-02-25 22:00
I have uploaded my save file to Bitwarden, you can download it from the link below. Note the link will expire after being accessed 3 times. Let me know if you have issues with it or would like me to send it in another way.
https://send.bitwarden.com/#-00vyV8mSUaz2LEhAWlUvA/43me4ujSoH5zt1bfHHCZ2g

I have also included a list of installed mods in that link as well. I will be updating to v6 as soon as I land my current vessel & will update you with the results. Thanks!

**Comment by Gschmidt22** [comment] 2024-02-25 23:44
Just tested with v6 and the issue is still occurring the same way as described earlier. Let me know if you would like me to send a new save with v6 installed. Thanks again!

**Comment by Gschmidt22** [comment] 2024-02-27 01:47
Another update, I was playing my save today and it appears to be working just fine with CommNext. I am no longer having the "No Power" message and my satellites stay connected even after quickloading! The only things that changed between my last comment and right now are:
1. I uninstalled the mod "Inputbinder" although I really doubt that was the issue
2. I restarted my computer

I appreciate your work on this mod! It makes the game much more engaging and challenging :)

**Comment by Erdemes** [comment] 2024-02-27 18:17
I still have the same issue with 0.6 version. I reinstalled the mod but no luck.

**Comment by Gschmidt22** [comment] 2024-02-27 18:33
Re-opening for @Erdemes

**Comment by rockfactory** [comment] 2024-02-29 00:37
@Erdemes @Gschmidt22 I've added a fix which should kick in automatically after ~10s from game load. Do you see it correctly updating after that time or nothing changes?
Could you send here the `Player.log` file? It's the one here:

```
C:\Users\<username>\AppData\LocalLow\Intercept Games\Kerbal Space Program 2\Player.log
```

**Comment by Gschmidt22** [comment] 2024-02-29 14:32
This issue started happening for me again today, I'd love to test the new fix and appreciate you being so quick with this. Is the new build published to CKAN? I can still only see v0.6.0 updated on 2/25

**Comment by Erdemes** [comment] 2024-02-29 16:59
@rockfactory I've waited for more than 10 seconds and nothing changed. In order to get the power back for all vessels, I have to get in control each of them. 
Here is the log
[Player.log](https://github.com/Kerbalight/CommNext/files/14451203/Player.log)

**Comment by rockfactory** [comment] 2024-03-01 00:53
> This issue started happening for me again today, I'd love to test the new fix and appreciate you being so quick with this. Is the new build published to CKAN? I can still only see v0.6.0 updated on 2/25

Unfortunately the (theoric) fix was _already_ in v0.6.0, so I suppose it's not sufficient. I'm starting to believe it's an issue with Background Processing for KSP2. I'll keep you updated if I can find something else

**Comment by rockfactory** [comment] 2024-03-01 23:05
@Erdemes could you share your save game and some screens / description? I tried to reload quicksaves with @Gschmidt22 save game but I cannot reproduce the issue

**Comment by Erdemes** [comment] 2024-03-02 07:17
@rockfactory  The problem is whenever I load my saved game (whether quick save or normal save). All of my vessels do not have any communication.
Here is the screenshot of the tracking station just after the fresh load.
![image](https://github.com/Kerbalight/CommNext/assets/73640165/a0ed99a7-1f91-48aa-89e3-41abd8c02b0c)

And here is another one controlling a vessel in a orbit. You can see that it shows they have no power in the comms report. But they have lots of power with batteries and panels extended.
![image](https://github.com/Kerbalight/CommNext/assets/73640165/0a9d3271-6863-45d4-b89a-482b68fabaa1)

In order to get the power back of all vessels. I have to get in control one by one.

Below is my modlist.
![image](https://github.com/Kerbalight/CommNext/assets/73640165/22715590-24f3-46e0-a7c9-240292a1c3e7)

And here are my save game files:
[SavedGame.zip](https://github.com/Kerbalight/CommNext/files/14468386/SavedGame.zip)

**Comment by rockfactory** [comment] 2024-03-04 22:55
Ok, finally I've got it fixed! The issue was in background EC processing, I couldn't reproduce it since it was enabled as a side-effect by Orbital Survey mod. I'm now implementing true energy consumption for relays; this will be available in next update

**Comment by rockfactory** [comment] 2024-03-06 01:07
This should be fixed in v0.7.0! Let me know

**Comment by Gschmidt22** [comment] 2024-03-06 15:53
I can confirm it is fixed for me, I appreciate you taking care of this!! Once again, your mod has made the game infinitely more enjoyable for me as I find the stock KSP 2 satellites way too easy. People like you are the reason this game is playable at this stage :)

I'll leave this issue open for a day or so in case someone else is still having the issue, but will close it soon assuming nobody else reports ongoing issues.

**Comment by rockfactory** [comment] 2024-03-06 18:01
> I can confirm it is fixed for me, I appreciate you taking care of this!! Once again, your mod has made the game infinitely more enjoyable for me as I find the stock KSP 2 satellites way too easy. People like you are the reason this game is playable at this stage :)
> 
> I'll leave this issue open for a day or so in case someone else is still having the issue, but will close it soon assuming nobody else reports ongoing issues.

Thanks for your kind words! Yes, I've got some other reports confirming this is working as intended, but let see what happens in the next days

**Comment by rockfactory** [comment] 2024-03-10 00:09
Seems everything's working now, I'm going to close this

**Closed as completed by rockfactory** 2024-03-10 00:09 UTC
Labels: bug
